language: ruby
rvm:
  - 2.4.5
matrix:
  include:
    - os: linux
    - os: osx
      osx_image: xcode10.2
      env: MACOSX_DEPLOYMENT_TARGET=10.14
    - os: osx
      osx_image: xcode9.4
      env: MACOSX_DEPLOYMENT_TARGET=10.13
cache:
  - apt
env:
  global:
    - secure: czDC2p9IxiWioyVqnFhupNYEAdNz/by2u0L7YC/yE9cmAFtVqXIf7nECaJSHusJH38/4ToA726PnlbPSA0FbcvepJz/sf8smEJbgjFJhm7SIMGP5nP4mqOf95oXvuz6pAkee1QR56THQq7y5UXFcl1JuXSAx6K7b8SMPE0q2r9Q=
    - RUBY_VERSION=2.4.5
before_install:
  - "./.travis_before_install.sh"
install:
  - rvm use ${RUBY_VERSION} --install --binary
  - rvm gemset create fresh
  - rvm ${RUBY_VERSION}@fresh
  - gem install bundler
  - cd ${TRAVIS_BUILD_DIR} && bundle install --jobs=3 --retry=3
script:
  - rvm use ${RUBY_VERSION}
  - rvm ${RUBY_VERSION}@fresh
  - bundle exec rake build
after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && GITHUB_TOKEN=$CI_USER_TOKEN node publish.js
