language: ruby
rvm:
  - 2.2
os:
  - linux
  - osx
cache:
  - apt
  - bundler
before_install:
  - ./.travis_before_install.sh
install:
  - cd ${TRAVIS_BUILD_DIR} && bundle install --jobs=3 --retry=3
script:
  - rake build
  - GITHUB_TOKEN=$CI_USER_TOKEN node publish.js
secure: "JarCEsEC4B29FttqeezwTrWsSQTyrK5YvUjSuN2BeWj+YPG2GAsEs8+MsyGilLOEIXuDkgViWySNX9Av9arq8l65jfWMI4zyHSKWEdbbqjxKUIgvVk/zW63tXUwnGruzeCAVj28tqzdXvJvokb5f5pCCZJh0v31/9oZehhp39Ik="
