language: ruby
rvm:
- 2.2
os:
- linux
- osx
cache:
- apt
- bundler
before_install:
- "./.travis_before_install.sh"
install:
- cd ${TRAVIS_BUILD_DIR} && bundle install --jobs=3 --retry=3
script:
- rake build
- GITHUB_TOKEN=$CI_USER_TOKEN node publish.js
CI_USER_TOKEN:
  secure: lLsghc79CLcD9RAMuLUAtL/2DfpJ92XDxfPRT3uojzV1XCWTksgEy0AobzC8P8KwGuPUKEgvxAAQBg1UpOT8JnywcPy1ahErJN8M3sF2zqzmXvDobUKKnIxAAn8tXPGwVOPfeWSDykKolK3Kc4cxAUVH6UBWsV6MuZljLFqqqys=
