language: ruby
rvm:
- 2.2
os:
- linux
- osx
cache:
- apt
- bundler
env:
  global:
    secure: czDC2p9IxiWioyVqnFhupNYEAdNz/by2u0L7YC/yE9cmAFtVqXIf7nECaJSHusJH38/4ToA726PnlbPSA0FbcvepJz/sf8smEJbgjFJhm7SIMGP5nP4mqOf95oXvuz6pAkee1QR56THQq7y5UXFcl1JuXSAx6K7b8SMPE0q2r9Q=
before_install:
- "./.travis_before_install.sh"
install:
- cd ${TRAVIS_BUILD_DIR} && bundle install --jobs=3 --retry=3
script:
- bundle exec rake build
- GITHUB_TOKEN=$CI_USER_TOKEN node publish.js
